name: trpo_5b_gf
entity: optimllab
project: fed_rl_energy
program: src/algos/trpo.py
command:
- ${env}
- ${interpreter}
- ${program}
- ${args}
- --wandb_logging
- --share_parameters_policy
- --share_parameters_critic
- --multiagent_ppo
- --group_features
method: grid
metric:
  goal: maximize
  name: eval/reward_mean
parameters:
  data_path:
    value: ./data/naive_5_buildings_simple/
  device:
    value: cuda
  reward:
    value: "weighted_cost_emissions"
  iterations:
    value: 30
  seed:
    values: [0, 1, 2, 3, 4]
  learning_rate:
    value: 0.0001
  epochs:
    values: 20
  days_in_iter:
    values: 500
  days_in_batch:
    value: 500