name: fed_avg_ppo_5_b_pe_exp
entity: optimllab
project: fed_rl_energy
program: src/algos/ppo.py
command:
- ${env}
- ${interpreter}
- ${program}
- ${args}
- --wandb_logging
- --personal_encoding
- --share_parameters_policy
- --share_parameters_critic
- --multiagent_ppo
method: grid
metric:
  goal: maximize
  name: eval/reward_mean
parameters:
  data_path:
    value: ./data/naive_5_buildings_simple/
  device:
    value: cuda
  reward:
    value: "weighted_cost_emissions"
  iterations:
    values: [30, 60, 90]
  seed:
    values: [0, 1, 2, 3, 4]
  learning_rate:
    value: 0.0001
  epochs:
    value: 50
  days_in_iter:
    value: 500
  days_in_batch:
    value: 100
  entropy_eps:
    value: 0.0001